import Head from 'next/head'

import { Header } from '@/components/Header/Header'
import { HeroSlider} from '@/components/HeroSlider/HeroSlider'
import { CompanyDescription } from '@/components/CompanyDescription/CompanyDescription'
import { MarketingCards } from '@/components/MarketingCards/MarketingCards'
import { ProductTrip } from '@/components/ProductTrip/ProductTrip'
import { Brands } from '@/components/Brands/Brands'
import { FollowUs } from '@/components/FollowUs/FollowUs'
import { Footer } from '@/components/Footer/Footer'

import styles from '@/styles/Page.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Techoutlet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={styles.page}
      >
        <Header />
        <main className={styles.main}>
          <HeroSlider />
          <CompanyDescription />
          <MarketingCards />
          <ProductTrip />
          <Brands />
          <FollowUs />
        </main>
        <Footer />
      </div>
    </>
  )
}
