import Head from "next/head"

import {Header} from "@/components/Header/Header"
import {Footer} from "@/components/Footer/Footer"

import styles from "@/styles/Page.module.scss"
import {HeroSlider} from "@/components/HeroSlider/HeroSlider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={styles.page}
      >
        <Header />
        <main className={styles.main}>
          <HeroSlider />
        </main>
        <Footer />
      </div>
    </>
  );
}
